name: Go

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
jobs:

  build:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Install yq
      run: sudo snap install yq

    - name: install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM }}

    - name: get Version
      run: echo "VERSION=$(sudo yq eval '.version' package.json)" >> $GITHUB_ENV

    - name: git tag
      run: git tag ${{ env.VERSION }} && git push origin ${{ env.VERSION }}

    - name: Update version environment variable
      run: export VERSION=$(echo ${{ env.VERSION }} | awk -F. '{print $1"."$2"."$3"."$4+1}')

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ github.ref }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
